### ISSUE TITLE
Remove unsafe code entirely

### ISSUE THREAD

**Issue by tazz4843** [top-gg/rust-sdk#12]
This crate seems absolutely ripe to get UB throughout, as it uses too much unsafe, and this wrapper should arguably never use unsafe at all, given it simply wraps a remote API and nothing more. I don't feel comfortable using this at all unless all of the unsafe were either removed or absolutely 100% asserted at compile time (and even then it's still iffy, as, again, realistically, such a crate should never use unsafe).

**Comment by null8626** [comment]
Thank you for your concerns. I've done several changes to minimize the chances of it UB-ing such as [adding safety comments](https://github.com/top-gg/rust-sdk/commit/9c4013afa1a709b2b9217edb7855acf48ab40cc6), [removing an unnecessary `unsafe` block](https://github.com/top-gg/rust-sdk/commit/0005d4e8b0b6b0ed9f67edb7ae632f34e096f565), and [removing all `unsafe` blocks from the documentation](https://github.com/top-gg/rust-sdk/commit/a251763c4858fcd58e4c6220149598fb51bc6fd1).

Is this enough or is there anything i can do? thanks!

**Comment by randomairborne** [comment]
there is no reason for this crate to use unsafe *at all*. I don't see why any of the remaining unsafe blocks couldn't be replaced with sane defaults, error handling, or at the very least a standard `unwrap`.

**Comment by null8626** [comment]
yeah i can see that - all unsafe should be removed by v1.2.1

**Comment by randomairborne** [comment]
Alright, wonderful. Thank you!
