### ISSUE TITLE
Autoposter ignores errors

### ISSUE THREAD

**Issue by valentinegb** [top-gg/rust-sdk#23]
When the autoposter calls `Client::post_stats()`, it ignores the result. This can make debugging very difficult if something goes wrong with the autoposter. Ideally, any errors would be propagated so they can be handled by the application however I understand that this may not possible. Alternatively, maybe any errors that do occur could be logged with `log` or `tracing`. Panicking in a separate thread is also an option.

**Comment by null8626** [comment]
Thank you for this suggestion!

**Comment by null8626** [comment]
Should be resolved by #25.
