### ISSUE TITLE
`Client::post_stats()` consistently returns `InternalServerError`

### ISSUE THREAD

**Issue by valentinegb** [top-gg/rust-sdk#24]
The following code:

```rs
topgg_client
    .post_stats(topgg::Stats::from_count(4, None))
    .await?;
```

returns `InternalServerError`. I believe that the autoposter is also failing due to `Client::post_stats()` failing.

... The error really doesn't say much, so this is all I can say ¯\\_(ツ)\_/¯

**Comment by null8626** [comment]
Thank you so much for this bug report. Will send a quick fix! :)

**Comment by null8626** [comment]
Should be resolved by #25.

**Comment by null8626** [comment]
This fix should take into effect by version 1.4.2, which would be released around 2 August UTC!

**Comment by valentinegb** [comment]
@null8626 thank you so much for swiftly taking care of everything I had to say yesterday! Especially #23, your solution is even better than what I suggested ^^

**Comment by null8626** [comment]
No worries! much love ❤️
