### ISSUE TITLE
HTTP/1.0 is deprecated

### ISSUE THREAD

**Issue by Xetera** [top-gg/rust-sdk#6]
Great job with this repo, looks amazing. Only one thing stood out to me, that it's not using HTTP/1.1 which every non http-2 client should be using instead of 1.0 that's been deprecated for like a decade

https://github.com/top-gg/rust-sdk/blob/27de52628e6c7c1890be84fccac734f7451040f9/src/http.rs#L46

**Comment by pixxies** [comment]
Deprecated for a decade? Just like everything else on Top gee gee. I see no issue here. 😂

**Comment by null8626** [comment]
~~fixed in #8.~~ fixed in #9.

**Comment by null8626** [comment]
again, thank you so much for the kind words <3

**Comment by null8626** [comment]
After some testing, apparently the Top.gg servers currently don't work with HTTP/1.1 - so i'm afraid this is a wontfix!

So yeah, the Top.gg servers themselves are the ones being outdated :)

**Comment by Xetera** [comment]
How did you test that?
```
curl https://top.gg/api --http1.1
```
works just fine for me. Same with
```
$ openssl s_client -connect top.gg:443
GET /api HTTP/1.1
Host: top.gg
User-Agent: curl
```
Unless specific api endpoints work differently which I don't think is the case

**Comment by null8626** [comment]
hmmm, that's weird - it might be a problem with my http handler - i'll look further into this

**Comment by null8626** [comment]
looks like i forgot to add the `Connection: close` header! now it works 😄

@pixxies see #9
